import '../CssFiles/Menu.css';
import { Button, Card, Container } from "react-bootstrap";
import { Link } from "react-router-dom";
import axios from "axios";
import { isAdmin } from '../utilities/utils';
function MenuItems(props) {

    //Reference: This line was generated by ChatGPT
    //props.isClickable checks if the isClickable property has been passed on, it expects a boolean value
    //props.onClick is the function that was called when the component gets clicked
    //undefined - if isClickable is false then it is set to undefined and will not trigger a click event handler
    //This is what allows the cards to be clicked on the addToDay.js component
    const ifClickAllowed = props.isClickable ? props.onClick : undefined;
    //declare these to allow me to use the remove from day function
    const { myMenuItem, onRemove } = props;

    return (
        <Container className="cardContainer" fluid>
            {/* Card holds all nessasary info about the item such as allergens, ingredients and price */}
            {/* {props.myMenuItem.variable} would show the data from the database */}

            {/* onClick={ifClickALlowed} is to allow on the addMeniItemToDay page for the card to be a clickable object*/}
            <Card className='cards' onClick={ifClickAllowed}>
                <Card.Body>
                    <Card.Title>{props.myMenuItem.name}</Card.Title>
                    {/* Blank cand text to space out the information */}
                    <Card.Text></Card.Text>
                    <Card.Subtitle>Allergens: </Card.Subtitle>
                    <Card.Text>{props.myMenuItem.allergens} </Card.Text>
                    <Card.Subtitle>Description:</Card.Subtitle>
                    <Card.Text>{props.myMenuItem.description}</Card.Text>
                    <Card.Subtitle>Price: €{props.myMenuItem.price}</Card.Subtitle>
                    <Card.Text></Card.Text>
                    {/* isAdmin() is from utils.js  -- This means the buttons are only visible if the user has entered the correct password */}
                    {isAdmin() && (
                        //this is brings you to the edit page and passes in the id in the url to edit that specific menu item
                        <Link to={'/EditMenuItem/' + props.myMenuItem._id} className="btn btn-primary" style={{width: 100}}>Edit</Link>
                    )}
                    <Card.Text></Card.Text>
                    {isAdmin() && (
                        //This button deletes the menu item with this id from the database entirely
                        //post request sends the password with it so the admin dont have to enter the password manually everytime they want to do something
                        <Button onClick={(e) => {
                            e.stopPropagation();//This line is to stop the onClick from remove affecting this click and triggering unwanted events
                            axios.post(`http://localhost:4000/menu_items/${props.myMenuItem._id}/delete`, { password: 'TestPassword' })
                                .then((res) => {
                                    props.Reload();//reload the cards without hitting the refresh button
                                })
                                .catch();
                        }} className='btn btn-danger' style={{width: 100}} >Delete</Button>
                    )}

                    <Card.Text></Card.Text>
                    {isAdmin() && (
                        //This button removes the menu item from the specific day of the week but doesnt delete it from the database
                        <Button variant="warning" onClick={() => onRemove(myMenuItem._id)}  style={{width: 100}}>
                            Remove from Day
                        </Button>
                    )}

                </Card.Body>
            </Card>
            <br></br>
        </Container>
    );

}

export default MenuItems;